### ISSUE TITLE
Missing case to call completion

### ISSUE THREAD

**Issue by ZhangChenglong** [comapi/comapi-sdk-ios#3] opened 2017-08-10 22:12 UTC
client.services.messaging.createConversation(newConversation) { result in
    print("result: ", result)
}
The print is never called. I look through the code, found that there is no code to call completion when got failure(let reason) which is not unauthorized case in "internal func performUsing<T: RequestTemplate>(templateBuilder: @escaping (_ token: String) -> T, completion: @escaping RequestTemplatePerformingCompletion<T.ResultType>)" of RequestManager.swift

**Comment by tomaszmaciejko** [comment] 2017-08-18 15:12
Hi @ZhangChenglong,

The code for returning completion blocks is returned by specified templates for each call, in this case it is PostConversationsTemplate. There you can find the logic responsible for handling completion blocks.

Testing on our side result in correct call for success and failure. If this is happening on the re-authentication flow it needs further analysis on our side. 

Please checkout the "dev" branch (further details on the issue #4) and report if the problem is still present.

Thanks, 
Tomasz

**Comment by ZhangChenglong** [comment] 2017-08-22 22:33
I think it is the reason I set the wrong role in ConversationParticipant. Now I get correct result by setting them "owner" or "participant".

Thanks,
Chenglong

**Comment by tomaszmaciejko** [comment] 2017-08-29 10:08
Closing as the issue is not present anymore.

**Closed by tomaszmaciejko** 2017-08-29 10:08 UTC
